### ISSUE TITLE
Not an Issue, just questions.

### ISSUE THREAD

**Issue by End-Effector** [warp1337/ros_aruco#2]
First, thx you so much for this pkg is amazing and it works really well.

I'm checking the code and there are lines that I don't understand why they are there.

1: ThePyroDownLevel its an Integer but is never inicialized, its used in a If avaliation. In line 162.

2: The code from line 68 to108, why is this code here? This code is used for changing images from openCV to Ros, but in this code we don't do that. In line 80 a subscriber to a non-existent topic.

3: A callback function that is never called, line 302

**Comment by hecsaniz** [comment]
Hi End-Effector,

I am trying to build this package but I am having problems.  I have followed all the steps of the "BUILDING AND USAGE" section but I get this error when I use the catkin_make command (step 7):

/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:50:1: error: ‘VideoCapture’ does not name a type
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp: In function ‘int main(int, char*)’:
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:131:2: error: ‘TheVideoCapturer’ was not declared in this scope
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:152:2: error: ‘namedWindow’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:153:2: error: ‘namedWindow’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:160:2: error: ‘createTrackbar’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:161:2: error: ‘createTrackbar’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:210:5: error: ‘Rodrigues’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:267:5: error: ‘imshow’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:268:5: error: ‘imshow’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:274:7: error: ‘waitKey’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp: In function ‘void cvTackBarEvents(int, void)’:
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:313:5: error: ‘imshow’ is not a member of ‘cv’
/home/laboratorio/catkin_ws/src/ros_aruco/ros_aruco/src/ros_aruco.cpp:314:5: error: ‘imshow’ is not a member of ‘cv’
make[2]: *** [ros_aruco/ros_aruco/CMakeFiles/ros_aruco.dir/src/ros_aruco.cpp.o] Error 1
make[1]: *** [ros_aruco/ros_aruco/CMakeFiles/ros_aruco.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed

Did you get the same error? How did you get it work?
I don't know why I get this error because I have followed all the steps. It would be great if you could help me. Thank you!
